version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_DB: linktic  
      POSTGRES_USER: admin     
      POSTGRES_PASSWORD: admin  
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  
    restart: unless-stopped

volumes:
  pgdata:
